minipipoblog_index:
      pattern:  /
      defaults: { _controller: minipipo1BlogBundle:Default:index }
      
minipipoblog_show:
      pattern: /article/voir/{id}
      defaults: { _controller: minipipo1BlogBundle:Default:view }
      requirements:
          id: \d+

minipipoblog_new:
      pattern: /article/ecrire
      defaults: { _controller: minipipo1BlogBundle:Default:new }
      
minipipoblog_edit:
      pattern: /article/modifier/{id}
      defaults: { _controller: minipipo1BlogBundle:Default:edit }
      requirements:
          id: \d+
      
minipipoblog_new_com:
      pattern: /com/ecrire
      defaults: { _controller: minipipo1BlogBundle:Default:newCom }

sdzblog_crud:
      resource: "routing/article.yml"
      prefix:   /crud
