minipipoblog_index:
      pattern:  /{page}
      defaults: { _controller: minipipo1BlogBundle:Default:index, page: 1 }
      requirements:
          page: \d+
      
minipipoblog_show:
      pattern: /article/voir/{id}
      defaults: { _controller: minipipo1BlogBundle:Default:view }
      requirements:
          id: \d+
          
minipipoblog_redac:
      pattern: /redaction
      defaults: { _controller: minipipo1BlogBundle:Default:list }
      
minipipoblog_del:
      pattern: /redaction/article/supprimer/{id}
      defaults: { _controller: minipipo1BlogBundle:Default:del }
      requirements:
          id: \d+

minipipoblog_new:
      pattern: /redaction/article/{id}
      defaults: { _controller: minipipo1BlogBundle:Default:new, id: 0 }
      requirements:
          id: \d+
      
minipipoblog_edit:
      pattern: /redaction/article/modifier/{id}
      defaults: { _controller: minipipo1BlogBundle:Default:edit }
      requirements:
          id: \d+
      
minipipoblog_new_com:
      pattern: /commentaire/ecrire
      defaults: { _controller: minipipo1BlogBundle:Default:newCom }

sdzblog_crud:
      resource: "routing/article.yml"
      prefix:   /crud
