parameters:
#    minipipo1_blog.example.class: minipipo1\BlogBundle\Example

services:
#    minipipo1_blog.example:
#        class: %minipipo1_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
