<?php

namespace minipipo1\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
        public function findAllDesc() {
                return $this->createQueryBuilder('a')
                                 ->orderBy("a.date", "DESC")
                                 ->getQuery()
                                 ->getResult();
        }
}