<?php

namespace minipipo1\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
        public function findAllDesc(Article $article) {
                return $this->createQueryBuilder('c')
                                 ->where("c.article = :article")
                                 ->setParameter("article", $article)
                                 ->orderBy("c.date", "DESC")
                                 ->getQuery();
        }
}